builders:
  localized_text_key_generator:
    import: "package:localized_text_key_generator/builder.dart"
    builder_factories: ["localizedWidgetGenerator"]
    auto_apply: dependents
    applies_builders: ["combining_builder"]
    build_to: source
    build_extensions:
      "$lib$": [".g.dart"]