name: localized_text_key_generator
description: Code generator that generates implementations of `LocalizedText` for the `localized_text_widget` package
version: 0.3.0
repository: https://github.com/dan3988/localized_text/tree/master/generator
resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  build: ^2.4.2
  build_config: ^1.1.2
  source_gen: ^2.0.0
  yaml: ^3.1.3
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  localized_text_widget: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
