name: localized_text_key_generator
description: Code generator that generates keys for .arb files
version: 0.1.0
repository: https://github.com/dan3988/localized_text/tree/master/generator
resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  build: ^2.4.2
  build_config: ^1.1.2
  source_gen: ^1.5.0
  yaml: ^3.1.3
  code_builder: ^4.10.1
  dart_style: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
