name: localized_text_widget
description: Use with the `localized_text_key_generator` package to simplify text widgets with localized text
version: 0.2.0
repository: https://github.com/dan3988/localized_text/tree/master/core
resolution: workspace

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
